import React, { useCallback, useState } from 'react';
import { Fields, FormValues, ValidationModes } from '../utils/fieldTypes';
import FormComponent from './Form';
import { RecaptchaConfig } from './useRecaptcha';

interface Config<T extends Fields> {
  /** The fields declaration */
  fields: T;

  /** The void function that fires on a form submission event */
  onSubmit: (
    formValues: FormValues<T>,
    helpers: { recaptchaToken: string },
  ) => void | Promise<void>;

  /** Add RECAPTCHA validation to the form */
  recaptcha?: RecaptchaConfig;

  /** The global form validation mode, defaults to ValidationModes.AFTER_BLUR */
  validationMode?: ValidationModes;
}

interface State {
  /** The form component generated by the hook */
  Form: () => JSX.Element;

  /** Helper state that indicates whether the form is submitting or not */
  submitting: boolean;
}

function useForm<T extends Fields>(config: Config<T>): State {
  //, deps?: DependencyList): State { // TODO add dependency list
  const [submitting, setSubmitting] = useState(false);
  const { fields, validationMode, onSubmit, recaptcha } = config;

  const Form = useCallback(
    () => (
      <FormComponent
        fields={fields}
        onSubmit={onSubmit}
        validationMode={validationMode}
        submitting={submitting}
        setSubmitting={setSubmitting}
        recaptcha={recaptcha}
      />
    ),
    [config, submitting],
  );

  return { Form, submitting };
}

export default useForm;
