import React, { DependencyList, ReactElement, useCallback } from 'react';
import Form from '../components/Form';
import { FieldPack, Fields, FormValues } from '../utils/helperTypes';
import { ValidationModes } from '../utils/validationTypes';
import { Config as RecaptchaConfig } from './useRecaptcha';

export interface Config<T extends Fields> {
  /** Required, the name of this form. Necessary for the use of IDs */
  name: string;

  /** Optional, defines the form fields used for this form */
  fieldPack?: FieldPack;

  /** Optional, defines the global form validation mode. Defaults to `ValidationModes.AFTER_BLUR` */
  validationMode?: ValidationModes;

  /** Required, declares the fields of the form */
  fields: T;

  /** Optional, adds a recaptcha check to the form */
  recaptcha?: RecaptchaConfig;

  /** Required, the void function that fires on a form submission event */
  onSubmit: (
    formValues: FormValues<T>,
    helpers: { recaptchaToken?: string },
  ) => void | Promise<void>;
}

export interface State {
  /** The form component generated by the hook */
  Form: () => ReactElement;
}

export default function useForm<T extends Fields>(
  config: Config<T>,
  deps?: DependencyList,
): State {
  const FormComponent = useCallback(() => <Form {...config} />, [config, deps]);
  return { Form: FormComponent };
}
